export type Flavor = 'javascript' | 'pcre' | 'python';

export interface Example {
  name: string
  pattern: string
  flags: string
  text: string
  desc: string
}

export interface CheatItem {
  syntax: string
  desc: string
}

export const examples: Record<Flavor, Example[]> = {
  javascript: [
    { name: 'Email parts', pattern: '([\\w.-]+)@([\\w.-]+)\\.(\\w+)', flags: 'g', text: 'Alice <alice@example.com> and Bob <bob@test.org>', desc: 'Captures username, domain, and TLD separately' },
    { name: 'URLs', pattern: 'https?:\\/\\/[\\w./_-]+', flags: 'g', text: 'Visit https://example.com/path or http://test.io', desc: 'Matches HTTP and HTTPS URLs' },
    { name: 'ISO dates', pattern: '(\\d{4})-(\\d{2})-(\\d{2})', flags: 'g', text: '2024-01-15 release, 2025-12-25 holiday', desc: 'Captures year, month, day groups' },
    { name: 'Phone numbers', pattern: '\\(?\\d{3}\\)?[-.\\s]?\\d{3}[-.\\s]?\\d{4}', flags: 'g', text: 'Call (555) 123-4567 or 555.987.6543', desc: 'Flexible phone format matcher' },
    { name: 'HTML tags', pattern: '<(\\w+)[^>]*>.*?<\\/\\1>', flags: 'g', text: '<div class="main"><p>hello</p></div>', desc: 'Matches paired HTML tags using backreference' },
    { name: 'Word boundary', pattern: '\\b\\w{4}\\b', flags: 'g', text: 'The quick brown fox jumps over the lazy dog', desc: 'Matches exactly 4-letter words' },
    { name: 'Password validation', pattern: '^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d)(?=.*[!@#$%]).{8,}$', flags: '', text: 'MyP@ss123', desc: 'Requires upper, lower, digit, special, 8+ chars' },
    { name: 'Named groups', pattern: '(?<year>\\d{4})-(?<month>\\d{2})-(?<day>\\d{2})', flags: 'g', text: 'Release: 2024-01-15, v2: 2025-06-30', desc: 'ES2018 named capture groups' },
    { name: 'Lookahead', pattern: '\\d(?=\\d{3})', flags: 'g', text: 'Subtotal: $1,234.56', desc: 'Digits followed by exactly 3 more digits' },
    { name: 'Lookbehind', pattern: '(?<=@)[\\w.]+', flags: 'g', text: 'user@example.com, admin@test.co.uk', desc: 'Matches domain after @ without including it' },
  ],
  pcre: [
    { name: 'Non-greedy tag', pattern: '<[^>]+>', flags: 'g', text: '<div><span>text</span></div>', desc: 'Matches each tag individually (not greedy)' },
    { name: 'Atomic group', pattern: '(?>a|ab)c', flags: '', text: 'abc', desc: 'Atomic group: once matched, never backtracks (won\'t match "ac")' },
    { name: 'Keep-out \\K', pattern: '\\w+@\\K\\w+', flags: 'g', text: 'alice@example.com bob@test.org', desc: '\\K resets match start - keeps only what follows' },
    { name: 'Backreference', pattern: '(\\w+)\\s+\\1', flags: 'g', text: 'the the word word hello', desc: 'Matches repeated words' },
    { name: 'Possessive quantifier', pattern: '\\w++\\s', flags: 'g', text: 'hello world', desc: 'Possessive ++ never gives up chars (try with "hello")' },
    { name: 'Nested recursion', pattern: '\\((?:[^()]|(?R))*\\)', flags: 'g', text: 'root (outer (inner) still) end', desc: 'Recursion matches nested parentheses' },
    { name: 'Branch reset', pattern: '(?|(a)|(b))', flags: 'g', text: 'a b', desc: 'Branch reset: both groups capture to \\1' },
    { name: 'Conditional', pattern: '(?(1)yes|no)', flags: '', text: 'yes', desc: 'Conditional: match "yes" if group 1 exists, else "no"' },
    { name: '\\G anchor', pattern: '\\G\\w', flags: 'g', text: 'abc def', desc: '\\G matches at start of string or end of last match' },
    { name: 'Callout', pattern: '(?C"debug")\\d+', flags: 'g', text: 'id: 42, code: 7', desc: 'PCRE callout - embeds external check (not supported in JS)' },
  ],
  python: [
    { name: 'Named groups', pattern: '(?P<name>\\w+)@(?P<domain>[\\w.]+)', flags: 'g', text: 'alice@example.com bob@test.org', desc: 'Python-style named groups with (?P<name>)' },
    { name: 'Non-capturing', pattern: '(?:foo|bar)+', flags: 'g', text: 'foobar barfoo', desc: 'Grouping without capturing' },
    { name: 'Lookbehind', pattern: '(?<=@)[\\w.]+', flags: 'g', text: 'user@example.com', desc: 'Positive lookbehind (also works in JS 2018+)' },
    { name: 'Unicode \\p{}', pattern: '\\p{L}+', flags: 'g', text: 'Café München 东京 århus', desc: 'Matches Unicode letters (any language)' },
    { name: 'Verbose mode', pattern: '\\d{4}  # year\\n-\\n\\d{2}  # month\\n-\\n\\d{2}  # day', flags: 'x', text: '2024-01-15', desc: 're.X / (?x) allows comments & whitespace' },
    { name: 'Inline flags', pattern: '(?i)hello', flags: 'g', text: 'Hello HELLO hello', desc: '(?i) turns on case-insensitivity mid-pattern' },
    { name: 'Backreference', pattern: '(?P<word>\\w+)\\s+(?P=word)', flags: 'g', text: 'the the word word', desc: 'Python named backreference (?P=name)' },
    { name: 'Lookahead', pattern: '\\d(?=\\d{2}[A-Z])', flags: 'g', text: 'A12B C34D', desc: 'Digit followed by 2 digits + uppercase' },
    { name: 'Possessive in 3.11+', pattern: '[A-Z]++\\d', flags: 'g', text: 'A1 B2', desc: 'Possessive quantifier (Python 3.11+)' },
    { name: 'Substitution', pattern: '(\\w+)@(\\w+)', flags: 'g', text: 'alice@example.com', desc: 'For re.sub: r"\\1 at \\2" replaces to "alice at example"' },
  ],
}

export const cheatSheet: Record<Flavor, CheatItem[]> = {
  javascript: [
    { syntax: '.', desc: 'Any character except newline' },
    { syntax: '\\d', desc: 'Digit [0-9]' },
    { syntax: '\\w', desc: 'Word character [a-zA-Z0-9_]' },
    { syntax: '\\s', desc: 'Whitespace [ \\t\\n\\r\\f]' },
    { syntax: '\\b', desc: 'Word boundary' },
    { syntax: '^', desc: 'Start of string / line (with m flag)' },
    { syntax: '$', desc: 'End of string / line (with m flag)' },
    { syntax: '*', desc: 'Zero or more (greedy)' },
    { syntax: '+', desc: 'One or more (greedy)' },
    { syntax: '?', desc: 'Zero or one (greedy)' },
    { syntax: '*? +? ??', desc: 'Lazy quantifiers (non-greedy)' },
    { syntax: '{n,m}', desc: 'Between n and m occurrences' },
    { syntax: '[...]', desc: 'Character class' },
    { syntax: '[^...]', desc: 'Negated character class' },
    { syntax: '(x)', desc: 'Capturing group' },
    { syntax: '(?:x)', desc: 'Non-capturing group' },
    { syntax: '(?=x)', desc: 'Lookahead (positive)' },
    { syntax: '(?!x)', desc: 'Lookahead (negative)' },
    { syntax: '(?<=x)', desc: 'Lookbehind (positive) - ES2018' },
    { syntax: '(?<!x)', desc: 'Lookbehind (negative) - ES2018' },
    { syntax: '(?<name>x)', desc: 'Named capturing group - ES2018' },
    { syntax: '\\k<name>', desc: 'Named backreference - ES2018' },
    { syntax: '\\1', desc: 'Backreference to group 1' },
    { syntax: 'g flag', desc: 'Global - find all matches' },
    { syntax: 'i flag', desc: 'Case-insensitive' },
    { syntax: 'm flag', desc: 'Multiline - ^/$ match line boundaries' },
    { syntax: 's flag', desc: 'DotAll - . matches newlines' },
    { syntax: 'u flag', desc: 'Unicode - enable \\p{} etc' },
    { syntax: 'y flag', desc: 'Sticky - match from lastIndex only' },
  ],
  pcre: [
    { syntax: '.', desc: 'Any character except newline' },
    { syntax: '\\d \\w \\s', desc: 'Shorthand classes (same as JS)' },
    { syntax: '\\b', desc: 'Word boundary' },
    { syntax: '^ $', desc: 'Start / end of string (or line in PCRE2)' },
    { syntax: '* + ?', desc: 'Greedy quantifiers' },
    { syntax: '*? +? ??', desc: 'Lazy quantifiers' },
    { syntax: '*+ ++ ?+', desc: 'Possessive quantifiers (no backtrack)' },
    { syntax: '{n,m}', desc: 'Range quantifier' },
    { syntax: '(?>x)', desc: 'Atomic group - no backtracking inside' },
    { syntax: '\\K', desc: 'Keep out - resets match start' },
    { syntax: '\\G', desc: 'Start of match / continuation anchor' },
    { syntax: '\\R', desc: 'Any newline sequence' },
    { syntax: '\\X', desc: 'Unicode grapheme cluster' },
    { syntax: '(?R)', desc: 'Recursion - match entire pattern again' },
    { syntax: '(?1)', desc: 'Subroutine call to group 1' },
    { syntax: '(?&name)', desc: 'Subroutine call to named group' },
    { syntax: '(?(cond)y|n)', desc: 'Conditional subpattern' },
    { syntax: '(?|a|b)', desc: 'Branch reset - groups share numbers' },
    { syntax: '(?C...)', desc: 'Callout - embed external function' },
    { syntax: '\\Q...\\E', desc: 'Quote - treat as literal text' },
    { syntax: '\\N{name}', desc: 'Named Unicode character' },
    { syntax: '\\h \\v', desc: 'Horizontal / vertical whitespace' },
    { syntax: '\\K', desc: 'Neovim: \\zs and \\ze do similar' },
    { syntax: '\\%^ \\%$', desc: 'Neovim: start / end of file (like \\A \\Z)' },
    { syntax: '\\%<line col', desc: 'Neovim: match at specific position' },
  ],
  python: [
    { syntax: '.', desc: 'Any character except newline' },
    { syntax: '\\d \\w \\s', desc: 'Shorthand classes' },
    { syntax: '\\D \\W \\S', desc: 'Negated shorthand classes' },
    { syntax: '\\b \\B', desc: 'Word boundary / non-boundary' },
    { syntax: '^ $', desc: 'Start / end of string (or line with re.M)' },
    { syntax: '* + ?', desc: 'Greedy quantifiers' },
    { syntax: '*? +? ??', desc: 'Lazy quantifiers' },
    { syntax: '{n,m} {n,}', desc: 'Range quantifier' },
    { syntax: '(?P<name>x)', desc: 'Named capturing group' },
    { syntax: '(?P=name)', desc: 'Named backreference' },
    { syntax: '(?:x)', desc: 'Non-capturing group' },
    { syntax: '(?=x) (?!x)', desc: 'Lookahead (positive / negative)' },
    { syntax: '(?<=x) (?<!x)', desc: 'Lookbehind (fixed-width only)' },
    { syntax: '(?>x)', desc: 'Atomic group (Python 3.11+)' },
    { syntax: '(?(cond)y|n)', desc: 'Conditional (Python 3.11+)' },
    { syntax: '(?iLmsux)', desc: 'Inline flags at pattern start' },
    { syntax: 're.A', desc: 'ASCII-only matching' },
    { syntax: 're.I', desc: 'Case-insensitive' },
    { syntax: 're.M', desc: 'Multiline - ^/$ match lines' },
    { syntax: 're.S', desc: 'DotAll - . matches newlines' },
    { syntax: 're.X', desc: 'Verbose - allow comments and whitespace' },
    { syntax: 're.UNICODE', desc: 'Unicode matching (default in Python 3)' },
    { syntax: '\\A \\Z', desc: 'Start / end of string (unaffected by re.M)' },
    { syntax: '\\b', desc: 'Word boundary (Unicode-aware in Python 3)' },
    { syntax: '\\p{L}', desc: 'Unicode category letter' },
  ],
}
