export type Difficulty = 'beginner' | 'easy' | 'medium' | 'hard' | 'expert'

export interface Exercise {
  id: string
  title: string
  difficulty: Difficulty
  category: string
  chapter: string
  desc: string
  hint: string
  text: string
  pattern: string
  flags: string
  explain: string
}

export const DIFFICULTIES: Difficulty[] = ['beginner', 'easy', 'medium', 'hard', 'expert']

const DIFF_MAP: Record<Difficulty, number> = {
  beginner: 1, easy: 2, medium: 3, hard: 4, expert: 5,
}

export function diffStars(d: Difficulty): string {
  return '●'.repeat(DIFF_MAP[d]).padEnd(5, '○')
}

export const exercises: Exercise[] = [
  {
    id: '01', title: 'Find "cat"', difficulty: 'beginner', category: 'Literal', chapter: 'literal',
    desc: 'Match the exact word **cat** wherever it appears.',
    hint: 'Just type the word itself - no special syntax needed.',
    text: 'The cat sat on the mat.\nCategory: feline.\nI like cats.',
    pattern: 'cat', flags: 'g',
    explain: 'The simplest regex is a literal string. `/cat/g` finds every occurrence of the characters c-a-t in sequence. Notice it also matches inside "Category" and "cats" - that\'s why word boundaries matter!',
  },
  {
    id: '02', title: 'Find any digit', difficulty: 'beginner', category: 'Character class', chapter: 'classes',
    desc: 'Match every single digit character in the text.',
    hint: 'Use the shorthand class for digits.',
    text: 'Room 42 has 3 chairs and 15 tables.\nFloor: 7.',
    pattern: '\\d', flags: 'g',
    explain: '`\\d` matches any digit `[0-9]`. Each digit is a separate match because we didn\'t combine them with a quantifier like `+`. Try `\\d+` to match consecutive digits as one match!',
  },
  {
    id: '03', title: 'Find letters', difficulty: 'beginner', chapter: 'classes', category: 'Character class',
    desc: 'Match every uppercase and lowercase letter.',
    hint: 'Use a character set with a range.',
    text: 'Hello World! 2024\nTest: ABC abc.',
    pattern: '[a-zA-Z]', flags: 'g',
    explain: '`[a-z]` matches any lowercase letter, `[A-Z]` matches uppercase. Combined as `[a-zA-Z]` we match any letter. This is called a character class - it matches ONE character from the set.',
  },
  {
    id: '04', title: 'Find word characters', difficulty: 'beginner', chapter: 'classes', category: 'Shorthand',
    desc: 'Match letters, digits, and underscores.',
    hint: 'There\'s a shorthand for word characters.',
    text: 'hello_world 123 !@#\nuser_name-42.',
    pattern: '\\w', flags: 'g',
    explain: '`\\w` is shorthand for `[a-zA-Z0-9_]` - word characters. Notice `-` and `!@#` and `.` are NOT matched. Underscores are included (it\'s useful for variable names).',
  },
  {
    id: '05', title: 'Find whitespace', difficulty: 'easy', chapter: 'classes', category: 'Shorthand',
    desc: 'Match spaces, tabs, and newlines.',
    hint: 'There\'s a shorthand for all whitespace.',
    text: 'a b\tc\n d\re',
    pattern: '\\s', flags: 'g',
    explain: '`\\s` matches spaces, tabs (`\\t`), newlines (`\\n`), carriage returns (`\\r`), and other whitespace. Each whitespace character is matched individually.',
  },
  {
    id: '06', title: 'Find non-digits', difficulty: 'easy', chapter: 'classes', category: 'Negation',
    desc: 'Match every character that is NOT a digit.',
    hint: 'Use the negated version of the digit shorthand.',
    text: 'Room 42, Door 7B\nPrice: $99!',
    pattern: '\\D', flags: 'g',
    explain: '`\\D` is the opposite of `\\d` - it matches anything that is NOT a digit. Uppercase shorthand classes always negate their lowercase counterparts.',
  },
  {
    id: '07', title: 'Match hex colors', difficulty: 'easy', category: 'Quantifier', chapter: 'classes',
    desc: 'Match 6-digit hex color codes (like `#ff0000`).',
    hint: 'A hex color starts with `#` followed by 6 hex chars.',
    text: '#ff0000 #00ff00 #0000ff\nInvalid: #xyz #ff', pattern: '#[0-9a-fA-F]{6}', flags: 'g',
    explain: '`{6}` is a quantifier meaning "exactly 6 of the preceding element". `[0-9a-fA-F]` matches hex digits. The `#` is a literal character. Together they match exactly `# + 6 hex chars`.',
  },
  {
    id: '08', title: 'Match vowels', difficulty: 'easy', chapter: 'classes', category: 'Character set',
    desc: 'Match all vowels (a, e, i, o, u) in any case.',
    hint: 'Write a character class containing just the vowels.',
    text: 'The quick brown fox jumps over the lazy dog.',
    pattern: '[aeiouAEIOU]', flags: 'g',
    explain: '`[aeiouAEIOU]` is a character class that matches ANY one character listed. Each vowel in the text gets matched individually. Notice "y" is NOT a vowel here (it\'s sometimes a vowel in English but not in this set).',
  },
  {
    id: '09', title: 'Match consonants', difficulty: 'easy', chapter: 'classes', category: 'Negation',
    desc: 'Match consonants - letters that are NOT vowels.',
    hint: 'Negate the vowel character class.',
    text: 'The quick brown fox jumps.',
    pattern: '[^aeiouAEIOU ]', flags: 'g',
    explain: '`[^...]` negates a character class - it matches anything NOT in the set. `[^aeiouAEIOU ]` matches consonants, digits, punctuation - but NOT vowels and NOT spaces. Try it with `[^aeiouAEIOU\\s]` to also exclude all whitespace.',
  },
  {
    id: '10', title: 'Three digits in a row', difficulty: 'easy', category: 'Quantifier', chapter: 'quantifiers',
    desc: 'Match exactly 3 consecutive digits.',
    hint: 'Use the exact count quantifier.',
    text: 'Call 911 or 555-1234.\nCode: 42, Pin: 9999.',
    pattern: '\\d{3}', flags: 'g',
    explain: '`\\d{3}` matches exactly 3 digits in a row. `911` and `555` match. `42` has only 2 digits so it doesn\'t match. `9999` has 4 digits - it matches the first 3 (`999`) and leaves the last `9`. Try `\\d{3,4}` to match 3 or 4 digits!',
  },
  {
    id: '11', title: 'One or more digits', difficulty: 'easy', chapter: 'quantifiers', category: 'Quantifier',
    desc: 'Match consecutive digits as a single match.',
    hint: 'Use the "one or more" quantifier.',
    text: 'Version 2.0.15\nCode: 42, id: 7.',
    pattern: '\\d+', flags: 'g',
    explain: '`\\d+` matches ONE or MORE consecutive digits. Unlike `\\d` (which matches each digit separately), `+` groups them: `15` is one match, `42` is one match, `7` is one match. This is a greedy quantifier - it takes as many as possible.',
  },
  {
    id: '12', title: 'Optional "colour"', difficulty: 'medium', chapter: 'quantifiers', category: 'Optional',
    desc: 'Match both "color" and "colour".',
    hint: 'The "u" is optional - make it optional in the pattern.',
    text: 'color favourite colour honor favourite flavor',
    pattern: 'colou?r', flags: 'g',
    explain: '`?` means "zero or one" of the preceding element. `colou?r` matches `c-o-l-o-u-r` or `c-o-l-o-r` (without the `u`). This is useful for British/American spelling differences.',
  },
  {
    id: '13', title: 'Phone number', difficulty: 'medium', category: 'Combining', chapter: 'quantifiers',
    desc: 'Match US phone numbers in `555-123-4567` format.',
    hint: 'Combine digit shorthands with literal hyphens and exact counts.',
    text: 'Call 555-123-4567 or 555-987-6543.\nInvalid: 555-12-345.',
    pattern: '\\d{3}-\\d{3}-\\d{4}', flags: 'g',
    explain: 'Three parts combined: 3 digits + hyphen + 3 digits + hyphen + 4 digits. `\\d{3}` matches the area code and exchange, `\\d{4}` matches the line number. The hyphens are literal characters.',
  },
  {
    id: '14', title: 'Whole word "cat"', difficulty: 'medium', chapter: 'anchors', category: 'Boundary',
    desc: 'Match "cat" only as a whole word, not inside other words.',
    hint: 'Use word boundaries `\\b` around the word.',
    text: 'cat category catalog dogcat cat\ncatherine',
    pattern: '\\bcat\\b', flags: 'g',
    explain: '`\\b` asserts a word boundary - the position between a word character and a non-word character. `\\bcat\\b` matches "cat" only when it stands alone, not inside "category" or "catalog".',
  },
  {
    id: '15', title: 'Five-letter words', difficulty: 'medium', category: 'Boundary', chapter: 'anchors',
    desc: 'Match words that are exactly 5 letters long.',
    hint: 'Combine word boundary with a word character quantifier.',
    text: 'The quick brown fox jumps over the lazy dog.',
    pattern: '\\b\\w{5}\\b', flags: 'g',
    explain: '`\\b\\w{5}\\b` matches exactly 5-letter words: "quick", "brown", "jumps", "lazy". The boundaries ensure we match whole words, and `{5}` ensures exactly 5 word characters.',
  },
  {
    id: '16', title: 'Lines starting with "Hello"', difficulty: 'medium', chapter: 'anchors', category: 'Anchors',
    desc: 'Match lines that start with "Hello".',
    hint: 'Use the start-of-line anchor with the multiline flag.',
    text: 'Hello world\nHi there\nHello again\nSay Hello',
    pattern: '^Hello', flags: 'gm',
    explain: '`^` is the start anchor. Without the `m` (multiline) flag, `^` matches only the start of the string. With `m`, it matches the start of every line. Only lines starting with "Hello" are matched.',
  },
  {
    id: '17', title: 'Cat or dog', difficulty: 'medium', chapter: 'groups', category: 'Alternation',
    desc: 'Match either "cat" or "dog".',
    hint: 'Use the alternation operator `|`.',
    text: 'I have a cat and a dog.\nThe dog chased the cat.',
    pattern: 'cat|dog', flags: 'g',
    explain: '`cat|dog` matches either "cat" OR "dog". The `|` operator has low precedence - it alternates between the whole expression on each side. For alternatives within a larger pattern, use groups: `(cat|dog)s` matches "cats" or "dogs".',
  },
  {
    id: '18', title: 'Capture date parts', difficulty: 'medium', category: 'Groups', chapter: 'groups',
    desc: 'Capture the year, month, and day from `YYYY-MM-DD` dates.',
    hint: 'Use parentheses to create capture groups for each part.',
    text: 'Today: 2024-01-15, tomorrow: 2024-01-16\nv2: 2025-12-25',
    pattern: '(\\d{4})-(\\d{2})-(\\d{2})', flags: 'g',
    explain: 'Each `()` creates a capture group: `(\\d{4})` captures the year, `(\\d{2})` captures month, `(\\d{2})` captures day. Click on a match to see the captured groups! This is how you extract structured data from text.',
  },
  {
    id: '19', title: 'Repeated words', difficulty: 'medium', chapter: 'groups', category: 'Backreference',
    desc: 'Find consecutive repeated words (like "the the").',
    hint: 'Capture a word with a group, then reference it with a backreference.',
    text: 'the the word word hello is is repeated\nand not this',
    pattern: '(\\w+)\\s+\\1', flags: 'g',
    explain: '`(\\w+)` captures a word into group 1. `\\s+` matches whitespace between them. `\\1` is a backreference - it matches the exact same text that was captured by group 1. This finds duplicate consecutive words!',
  },
  {
    id: '20', title: 'URL with optional protocol', difficulty: 'medium', category: 'Non-capturing', chapter: 'groups',
    desc: 'Match URLs with or without `https://` prefix.',
    hint: 'Make the protocol part optional with a non-capturing group.',
    text: 'https://example.com http://test.io\nsite.com https://a.io',
    pattern: '(?:https?://)?[\\w.-]+\\.[a-z]{2,}', flags: 'g',
    explain: '`(?:...)` is a non-capturing group - it groups without capturing. `(?:https?://)?` makes the protocol optional. `[\\w.-]+` matches the domain name, `\\.[a-z]{2,}` matches the TLD (.com, .org, etc.).',
  },
  {
    id: '21', title: 'Digits before "px"', difficulty: 'hard', chapter: 'lookaround', category: 'Lookahead',
    desc: 'Match digits that are immediately followed by "px".',
    hint: 'Use a positive lookahead to check what comes after.',
    text: 'Width: 100px, Height: 200px\nMargin: 15, Padding: 8px',
    pattern: '\\d+(?=px)', flags: 'g',
    explain: '`(?=px)` is a positive lookahead - it asserts that "px" follows the digits, but does NOT include "px" in the match. So `100px` matches just `100`. This is great for conditional matching without consuming characters.',
  },
  {
    id: '22', title: 'Not "cat" words', difficulty: 'hard', category: 'Negative lookahead', chapter: 'lookaround',
    desc: 'Match all 3-letter words except the word "cat".',
    hint: 'Combine negative lookahead with word boundary.',
    text: 'cat bat rat cat mat\nsat fat cat',
    pattern: '\\b(?!cat\\b)\\w{3}\\b', flags: 'g',
    explain: '`(?!cat\\b)` is a negative lookahead - it asserts that "cat" does NOT appear at this position. Combined with `\\b\\w{3}\\b` (any 3-letter word), this matches all 3-letter words EXCEPT "cat".',
  },
  {
    id: '23', title: 'Price after $', difficulty: 'hard', category: 'Lookbehind', chapter: 'lookaround',
    desc: 'Match prices that come after a dollar sign.',
    hint: 'Use a positive lookbehind to check what comes before.',
    text: 'Price: $25.99, Cost: $100\nValue: 50€, Sale: $9.99',
    pattern: '(?<=\\$)\\d+(?:\\.\\d{2})?', flags: 'g',
    explain: '`(?<=\\$)` is a positive lookbehind - it asserts that a `$` comes before the digits, without including it in the match. `\\d+(?:\\.\\d{2})?` matches the dollar amount with optional cents.',
  },
  {
    id: '24', title: 'Email addresses', difficulty: 'hard', chapter: 'practical', category: 'Practical',
    desc: 'Match email addresses and capture username, domain, and TLD.',
    hint: 'Capture three parts: username @ domain . tld.',
    text: 'Contact: alice@example.com\nAdmin: bob.smith@gmail.org\nSpam: test@co.uk',
    pattern: '([\\w.-]+)@([\\w.-]+)\\.(\\w+)', flags: 'g',
    explain: 'Three capture groups: `([\\w.-]+)` matches the username (word chars, dots, hyphens), `([\\w.-]+)` matches the domain, `(\\w+)` matches the TLD. Notice "co.uk" captures "co" as domain and "uk" as TLD - real email parsing is more complex!',
  },
  {
    id: '25', title: 'Full URLs', difficulty: 'hard', chapter: 'practical', category: 'Practical',
    desc: 'Match full URLs including paths and query parameters.',
    hint: 'Start with `https://`, then match the path and query.',
    text: 'Visit https://example.com/path?q=search\nhttp://site.net/page?id=1&ref=2\nftp://ignore.me',
    pattern: 'https?://[\\w./?=&%-]+', flags: 'g',
    explain: '`https?://` matches the protocol (with optional s). `[\\w./?=&%-]+` matches the domain, path, and query parameters. Notice `ftp://` is NOT matched because we only match `http` or `https`.',
  },
  {
    id: '26', title: 'Named date groups', difficulty: 'hard', category: 'Named groups', chapter: 'groups',
    desc: 'Extract date parts using named capture groups.',
    hint: 'Use `(?<name>...)` syntax for named groups.',
    text: 'Release: 2024-06-30, v2: 2025-01-15\nDeadline: 2024-12-31',
    pattern: '(?<year>\\d{4})-(?<month>\\d{2})-(?<day>\\d{2})', flags: 'g',
    explain: 'Named groups use `(?<name>...)` syntax. Here we name them `year`, `month`, and `day`. Click on a match and see "Named groups" listed with their names instead of just numbers. Much more readable!',
  },
  {
    id: '27', title: 'Strong password', difficulty: 'hard', category: 'Lookahead', chapter: 'lookaround',
    desc: 'Match passwords with uppercase, lowercase, digit, special char, 8+ chars.',
    hint: 'Stack multiple lookaheads at the start. Each asserts one requirement.',
    text: 'Weak\nStrong1!\nNoDigits!\nlowercase1A\ng00dP@ss!',
    pattern: '^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d)(?=.*[^a-zA-Z\\d]).{8,}$', flags: '',
    explain: 'This uses 4 lookaheads: `(?=.*[A-Z])` requires an uppercase, `(?=.*[a-z])` requires lowercase, `(?=.*\\d)` requires a digit, `(?=.*[^a-zA-Z\\d])` requires a special char. Then `.{8,}` matches 8+ characters. Each lookahead checks the whole string without consuming it.',
  },
  {
    id: '28', title: 'HTML tags', difficulty: 'hard', chapter: 'practical', category: 'Backreference',
    desc: 'Match paired HTML tags with their content.',
    hint: 'Capture the tag name and use a backreference for the closing tag.',
    text: '<div><p>text</p><span>hi</span></div>\n<br/><img/>',
    pattern: '<(\\w+)[^>]*>.*?</\\1>', flags: 'g',
    explain: '`<(\\w+)` captures the tag name. `[^>]*>` matches attributes and the closing `>`. `.*?` matches the content (lazy - the `?` makes it non-greedy). `</\\1>` uses a backreference to match the closing tag. `<br/>` and `<img/>` don\'t match because they have no closing tag.',
  },
  {
    id: '29', title: 'IPv4 addresses', difficulty: 'expert', category: 'Complex', chapter: 'practical',
    desc: 'Match IPv4 addresses like `192.168.1.1`.',
    hint: 'Four octets of 1-3 digits separated by dots.',
    text: 'Server: 192.168.1.1, GW: 10.0.0.1\nInvalid: 999.999.999.999\nLoopback: 127.0.0.1',
    pattern: '\\b(?:\\d{1,3}\\.){3}\\d{1,3}\\b', flags: 'g',
    explain: '`(?:\\d{1,3}\\.){3}` matches an octet + dot, exactly 3 times (non-capturing). Then `\\d{1,3}` matches the final octet. Word boundaries ensure we don\'t match partial octets. Note: this doesn\'t validate 0-255 range (that requires more complex logic).',
  },
  {
    id: '30', title: 'Hex or RGB colors', difficulty: 'expert', category: 'Alternation', chapter: 'practical',
    desc: 'Match both hex colors (`#ff0000`) and RGB colors (`rgb(255,0,0)`).',
    hint: 'Use alternation to match either format.',
    text: 'color: #ff0000; background: rgb(255,0,0);\nborder: #00f; outline: rgb(0,255,0);',
    pattern: '#[0-9a-fA-F]{3,6}\\b|rgb\\(\\d{1,3},\\s*\\d{1,3},\\s*\\d{1,3}\\)', flags: 'g',
    explain: 'Two alternatives separated by `|`. The left side matches hex colors (`#` + 3-6 hex digits). The right side matches `rgb(r,g,b)` with digits separated by commas and optional spaces. Notice the `\\(` escaping parentheses since they\'re special in regex.',
  },
  {
    id: '31', title: 'Time in HH:MM', difficulty: 'medium', category: 'Pattern', chapter: 'quantifiers',
    desc: 'Match time values in 24-hour format (HH:MM).',
    hint: 'Two digits, colon, two digits.',
    text: 'Meeting at 14:30, lunch at 12:00\nBreak at 09:15, invalid: 25:70',
    pattern: '\\b\\d{2}:\\d{2}\\b', flags: 'g',
    explain: '`\\d{2}:\\d{2}` matches two digits, colon, two digits. Word boundaries ensure we don\'t match partial patterns. This matches valid and invalid times - advanced patterns can validate hours 00-23 and minutes 00-59.',
  },
  {
    id: '32', title: 'Semantic versions', difficulty: 'hard', chapter: 'practical', category: 'Pattern',
    desc: 'Match semver strings like `1.2.3` or `2.0.0`.',
    hint: 'Three numbers separated by dots.',
    text: 'Version 1.2.3 and 2.0.0-alpha\n3.0.0 is next, not 1.2 or .3.4.',
    pattern: '\\b\\d+\\.\\d+\\.\\d+\\b', flags: 'g',
    explain: '`\\d+\\.\\d+\\.\\d+` matches major.minor.patch. Word boundaries prevent matching partial versions. This matches `1.2.3`, `2.0.0`, `3.0.0` but not `1.2` or `.3.4`. For semver with pre-release tags, you\'d extend it.',
  },
  {
    id: '33', title: 'Match any character', difficulty: 'beginner', category: 'Wildcard', chapter: 'literal',
    desc: 'Use the dot `.` to match any character followed by `at`.',
    hint: 'The dot is a special metacharacter that stands in for any single character.',
    text: 'cat bat rat mat\nhot pot dot',
    pattern: '.at', flags: 'g',
    explain: '`.` matches any single character except a newline. `.at` matches "cat", "bat", "rat", "mat", "hot", "pot", "dot" - any character followed by "at". To match a literal dot, you must escape it: `\\.`',
  },
  {
    id: '34', title: 'Match a literal dot', difficulty: 'easy', category: 'Escaping', chapter: 'literal',
    desc: 'Match only the dots in version numbers - not just any character.',
    hint: 'A dot is a metacharacter. Prefix it with `\\` to treat it as literal.',
    text: 'v1.2.3 is stable\nv1 2 3 is not a version',
    pattern: '\\.', flags: 'g',
    explain: 'Without escaping, `.` matches any character - including spaces and letters. `\\.` escapes the dot so it only matches a literal period. The same rule applies to all metacharacters: `\\*`, `\\+`, `\\(`, `\\)`, `\\[`, etc.',
  },
  {
    id: '35', title: 'Zero or more !', difficulty: 'easy', category: 'Quantifier', chapter: 'quantifiers',
    desc: 'Match `ha` followed by any number of exclamation marks - including none.',
    hint: 'Use `*` for zero or more repetitions.',
    text: 'ha ha! ha!! ha!!! nice',
    pattern: 'ha!*', flags: 'g',
    explain: '`*` means zero or more of the preceding element. `ha!*` matches "ha" with any number of `!`s - including zero. Unlike `+` (one or more), `*` succeeds even when the element is absent. "nice" does not match because it does not start with "ha".',
  },
  {
    id: '36', title: '4 to 6 letter words', difficulty: 'medium', category: 'Quantifier', chapter: 'quantifiers',
    desc: 'Match words that are between 4 and 6 letters long.',
    hint: 'Use a range quantifier `{min,max}` combined with word boundaries.',
    text: 'Go hit over the quick brown fox near here',
    pattern: '\\b[a-zA-Z]{4,6}\\b', flags: 'g',
    explain: '`{4,6}` matches between 4 and 6 of the preceding element. With `\\b` for word boundaries and `[a-zA-Z]` for letters, this matches "over" (4), "quick" (5), "brown" (5), "near" (4), "here" (4). "hit", "the", "fox", and "Go" are too short.',
  },
  {
    id: '37', title: 'Lines ending with a period', difficulty: 'medium', category: 'Anchors', chapter: 'anchors',
    desc: 'Match lines that end with a period.',
    hint: 'Use the end-of-line anchor with the multiline flag.',
    text: 'Hello world.\nNo period here\nThis ends with a dot.\nLast line',
    pattern: '.+\\.$', flags: 'gm',
    explain: '`$` is the end anchor. Without `m` it only matches the very end of the whole string. With `m` (multiline), `$` matches the end of every line. `.+` matches one or more characters, `\\.` matches a literal dot, and `$` asserts that dot is at the line\'s end.',
  },
  {
    id: '38', title: 'Case-insensitive match', difficulty: 'easy', category: 'Flags', chapter: 'literal',
    desc: 'Match the word `regex` regardless of capitalisation.',
    hint: 'Use the flag that ignores case differences.',
    text: 'Regex is fun. REGEX is powerful. regex is useful.',
    pattern: 'regex', flags: 'gi',
    explain: 'The `i` flag makes the pattern case-insensitive. `/regex/gi` matches "Regex", "REGEX", and "regex". Without `i`, only the exact lowercase form would match. Combine with `g` to find all occurrences.',
  },
  {
    id: '39', title: 'Lazy vs greedy', difficulty: 'hard', category: 'Lazy', chapter: 'quantifiers',
    desc: 'Extract each quoted string separately using a lazy quantifier.',
    hint: 'Add `?` after your quantifier to make it stop at the earliest possible match.',
    text: '"hello" and "world" and "regex"',
    pattern: '".*?"', flags: 'g',
    explain: '`.*` is greedy - it matches as much as possible. `".*"` would match from the first `"` all the way to the last `"` as one huge match. `.*?` is lazy - it matches as little as possible - so `".*?"` stops at the first closing quote, giving three separate matches.',
  },
  {
    id: '40', title: 'Numbers not after $', difficulty: 'hard', category: 'Negative lookbehind', chapter: 'lookaround',
    desc: 'Match numbers that are NOT preceded by a dollar sign.',
    hint: 'Use a negative lookbehind to exclude values after `$`.',
    text: 'Score: 42, $100 prize, 7 items, $500 reward',
    pattern: '(?<!\\$)\\b\\d+\\b', flags: 'g',
    explain: '`(?<!\\$)` is a negative lookbehind - it asserts that `$` does NOT immediately precede this position. Combined with `\\b\\d+\\b` (whole numbers), only "42" and "7" match. "100" and "500" are excluded because they follow a dollar sign.',
  },
]
